[package]
name = "station_iapetus"
version = "0.4.0"
edition = "2021"

[dependencies]
fyrox = { workspace = true }
ron = "0.8.1"
serde = "^1.0.0"
strum = "0.27"
strum_macros = "0.27"
chrono = "0.4.33"

[features]
default = ["fyrox/default"]
dylib-engine = ["fyrox/dylib"]